version: 2
updates:
- package-ecosystem: npm
  directory: "/themes/vuetober"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: sass-loader
    versions:
    - 11.0.0
